### ISSUE TITLE
Show Faction Members

### ISSUE THREAD

**Issue by Spidi** [webbukkit/Dynmap-Factions#2]
as part of the new login system it would be nice if maybe i could give users the permissions 'dynmap.factions' and then they would be able to see all members of their faction on the Dynmap. I understand that this could be an epic task as it took me a little while to get the JSON Login system working correctly on my Server, and making it look how i wanted :)

**Comment by mikeprimm** [comment]
Just completed this in the 0.20 release (requires 0.60 dynmap update, too).  The 'visibility-by-factions' setting enables support for faction members to see one another on the map (in conjunction with using the login support and having turned on the player-info-protected feature to hide players from one another).

**Comment by Spidi** [comment]
Thanks Mate, I'm switching to Towny now but it's nice to see you added the feature on that plugin as well :)

**Comment by mikeprimm** [comment]
For sure - give it a go, and let me know if you have any more suggestions on how to best support the feature.
