### ISSUE TITLE
BukkitForge compatability

### ISSUE THREAD

**Issue by SquaredTiki** [webbukkit/Dynmap-Factions#7]
At the moment I am using the Forge version of Dynmap as I am running a  server with BukkitForge installed however I also have a number of plugins installed including Factions and Essentials. Is there any way to  use these plugins with the Forge version of Dynmap which is running on a BukkitForge server?

**Comment by mikeprimm** [comment]
As of the new 1.6 recommended build, you can do the following:
1) Install the appropriate forge version of dynmap (1.4.7, I'm assuming, unless you're using BukkitForge on a 1.5.1)
2) Install the DynmapCBBridge plugin (this is a bukkit plugin that makes DynmapForge look like Dynmap-for-Bukkit for the sake of other bukkit plugins, such as dynmap-mobs or Dynmap-Factions.

**Comment by SquaredTiki** [comment]
Ahh excellent, if only I'd looked through the list of other repositiories a little bit more thoroughly I would have noticed that. 

Unfortunately while the plugins all seem to load each of them produce the following error:

```
SEVERE [Dynmap-Essentials] Error loading Dynmap marker API!
```

**Comment by SquaredTiki** [comment]
Any ideas?

Other reports of this suggest that there are other errors/warnings displayed however for me this is the only warning displayed.

**Comment by mikeprimm** [comment]
Are you running the RB level of both DynmapForge and DynmapCBBridge (1.6 - not an earlier dev build or alpha of 1.6)?  I've got Dynmap-Essentials running fine with it.  Any earlier versions will likely get that error.

**Comment by SquaredTiki** [comment]
I downloaded the recommended version (1.6) for v1.4.7 of Minecraft from here: http://www.minecraftforum.net/topic/1543523-dynmap-dynamic-web-based-maps-for-minecraft/

**Comment by SquaredTiki** [comment]
Sorry I was mistaken, I seemed to have been running 1.5. Updating it corrected everything, sorry for the inconvenience.

Thanks!

**Comment by SquaredTiki** [comment]
Sorry to bother you again.  All of the plugins load correctly without any errors and they are displayed in the little layer selection part of dynmap however nothing is ever overlayed onto the map despite regions such as WorldGuard, Factions and mobs existing. Here's my dynmap if it helps: http://192.95.29.208:8123/#

Thanks
