### ISSUE TITLE
Does not draw or draw incomplete factions regions

### ISSUE THREAD

**Issue by SleepyPrince** [webbukkit/Dynmap-Factions#8]
I am getting this since v0.50 with Factions 2.0.1 and mcore 6.4.1
 [WARNING] [Dynmap-Factions] Task #2121 for Dynmap-Factions v0.50 generated an exception java.lang.NullPointerException at org.dynmap.factions.DynmapFactionsPlugin.updateFactions(DynmapFactionsPlugin.java:521) at org.dynmap.factions.DynmapFactionsPlugin.access$000(DynmapFactionsPlugin.java:52) at org.dynmap.factions.DynmapFactionsPlugin$FactionsUpdate.run(DynmapFactionsPlugin.java:136) at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftTask.run(CraftTask.java:53) at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345) at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:513) at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226) at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477) at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410) at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)

The regions are either not drawn at all or partially drawn

**Comment by SleepyPrince** [comment]
I think I have found the problem that caused that error
Line 521 in DynmapFactionsPlugin.java
home = set.createMarker(markid, lbl, homeloc.getWorld(),
                                    homeloc.getBlockX(), homeloc.getBlockY(), homeloc.getBlockZ(), ico, false);

I think getBlockX, Y and Z should be replaced by getLocationX, Y and Z.
As long as you don't do /f sethome, the plugin works fine

**Comment by mikeprimm** [comment]
Problem should be fixed in current dev build - will release update shortly

**Comment by mikeprimm** [comment]
Fix released
